### ISSUE TITLE
Can you make this for server side installation only?

### ISSUE THREAD

**Issue by DingoX3** [JackyyTV/SkyIslandsCreator#1]
As most of these packs are already out or not in development anymore, its a major issue to ask all your players to install this mod before joining your server. Most of our players can figure it out but then there are those that can hardly open the twitch launcher. So if you could make this server-side only that would be great. Thanks

**Comment by JackyyTV** [comment]
This mod should be able to run on server side only (just like morpheus) without any problems, unless I forgot to specify that in the codes, will double check first.

**Comment by JackyyTV** [comment]
Just checked, my bad, the mod was meant to be able to run on server side only without any problems, but apparently not. Will fix that now.

**Comment by JackyyTV** [comment]
1.1 update is available on CurseForge, grab whichever MC version you need (1.10.2 / 1.11.2 / 1.12.x).

**Comment by DingoX3** [comment]
Awesome thanks. With plugins still being worked on this will make a great mod/plugin to allow players to create islands on our server.
